aws:
  s3:
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}
  cloudfront:
    endpoint: ${AWS_CLOUDFRONT_ENDPOINT}
  credentials:
    keys:
      access: ${AWS_CREDENTIALS_ACCESS_KEY}
      secret: ${AWS_CREDENTIALS_ACCESS_SECRET}
jwt:
  expires: ${JWT_EXPIRES:300000}
  secret: ${JWT_SECRET:a8127e4ac3051606e14599e584425b1e756b0be392a546111096c4946ca324f8}
  issuer: ${JWT_ISSUER:falabella-campaigns-backend}
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5434/campaigns}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: ${MAX_POOL_SIZE:20}
      minimum-idle: ${MIN_POOL_SIZE:10}
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      auto-commit: true
      pool-name: HikariPool-1
      initialization-fail-timeout: 1
      validation-timeout: 5000
      leak-detection-threshold: 2000
      register-mbeans: false
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:true}
    open-in-view: false
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    url: ${FLYWAY_URL:jdbc:postgresql://localhost:5434/campaigns}
    user: ${FLYWAY_USER:postgres}
    password: ${FLYWAY_PASSWORD:postgres}
springdoc:
  api-docs:
    path: ${SPRINGDOC_PATH:/api/docs}
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_PATH:/api/swagger/}
    operations-sorter: method
logging:
  level:
    org.hibernate.orm.connections.pooling: WARN
    com.zaxxer.hikari: WARN
    org.hibernate: INFO
server:
  port: ${SERVER_PORT:8080}