CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    firstname VARCHAR(32),
    lastname VARCHAR(32),
    document VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);